topics:
  #real sense camera
  #rgb: "/camera/color/image_raw"
  #depth: "/camera/aligned_depth_to_color/image_raw"
  #zed camera
  rgb: "/rgb/image_rect_color"
  depth: "/depth/depth_registered"
  out: "pcloud"
camera:
  #real sense parameters
  #k: [608.8712768554688, 608.888427734375, 323.6396789550781, 244.1296844482422]
  #d: 2
  #scale: 0.001

  #zed parameters
  k: [349.7, 339.9, 349.7, 172.9]
  d: 4
  scale: 1.0